version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./apis/video-streaming
      dockerfile: dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"
